apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs
            name: web
      volumes:
      - name: web
        persistentVolumeClaim:
          claimName: hostpath-pvc
