apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret
  labels:
    name: mypod-secret
spec:
  containers:
  - name: mypod-secret
    image: redis
    volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: mysecret-manifest