version: "3.1"
services:
  mysqlDB:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "mspassword"
      MYSQL_DATABASE: "meh"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.name == personal-laptop